### DISCUSSION TITLE
Cool Feature Ideas

### DISCUSSION THREAD

**Discussion by woooferz** [woooferz/skarf#24] [Ideas]
If you have a cool idea for a new feature, use this!

**Comment by xstar97** [comment]
alternatively set up env variables instead config files

```yaml
CONFIG_JSON: { "version": 10,"static": false,"debug": false......}
```
______
```yaml
VERSION: 10
STATIC: false
.......
```
